### PR TITLE
fix(s3stream/wal): fix read file

### LINKED ISSUE #614: WALFileChannel#read depends on implementation instead of API
5bef5e09-747c-4e4d-8eed-300b2eea8c00
632eb0fd-8eaf-4efe-a81e-73a9881b7e27

### PR DESCRIPTION
**Pull request by Chillax-0v0**
fix #614

### CODE REVIEW

File: s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ public long capacity() {
 
     @Override
     public void write(ByteBuf src, long position) throws IOException {
-        assert src.readableBytes() + position <= fileCapacityFact;
+        assert src.readableBytes() + position <= capacity();
```
Comment (mooc9988) [inline s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java:90]: assert will only work if it is enabled in JVM options. It may be better to use Preconditions or just throw IllegalArgumentException here.

**Review by mooc9988 — APPROVED** [review]
